package com.store.Store.model;


import jakarta.persistence.*;

// @Entity indicates that the class is a JPA entity object which is mapped to a database table
@Entity
@Table(name = "addresses")
public class Address {
    // @Id indicates that the field is the primary key
    // @GeneratedValue indicates that the primary key is generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private Integer number;
    // @Column indicates that the field is mapped to a database column
    @Column(name = "Street")
    private String streetAddress;
    private String postcode;

    public Address(Integer number, String streetAddress, String postcode) {
        this.number = number;
        this.streetAddress = streetAddress;
        this.postcode = postcode;
    }

    // Default constructor required by JPA
    public Address() {

    }

    public Integer getId() {
        return id;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getStreet() {
        return streetAddress;
    }

    public void setStreet(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
}
